formatter: "markdown"

version: ""

header-from: README.md
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: 
    - all



content: |-
  ### main.tf

  ```hcl
  {{ include "Tests/main.tf" }}
  ```
  
  ----------------------------

  # Input Description
  
  {{ .Requirements }}  

  {{ .Providers }}  

  {{ .Modules }}  

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true