version: 2
updates:
  - package-ecosystem: 'terraform'
    directories:
      - "./Tests"
    schedule:
      interval: 'daily'
    # Raise pull requests for version updates
    # to pip against the `dev` branch
    target-branch: "dev"
    ignore:
      - dependency-name: "*git*"
      - dependency-name: "*ssh*"      
